<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class EstudianteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('estudiantes')->insert([[
            'nacionalidad_id' => 1,
            'guardian_id' => 1,
            'nombre' => 'Lucius',
            'apellido' => 'Payne',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '2984724',
            'fecha_nacimiento' => '2003/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 2,
            'guardian_id' => 2,
            'nombre' => 'Chad',
            'apellido' => 'Sanchez',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '3565445',
            'fecha_nacimiento' => '2003/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 3,
            'guardian_id' => 1,
            'nombre' => 'Michael',
            'apellido' => 'Wise',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '8734373',
            'fecha_nacimiento' => '2003/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 2,
            'guardian_id' => 2,
            'nombre' => 'Sharon',
            'apellido' => 'Williams',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '9842438',
            'fecha_nacimiento' => '2003/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 2,
            'guardian_id' => 3,
            'nombre' => 'Willis',
            'apellido' => 'McGee',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '6387258',
            'fecha_nacimiento' => '2004/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 1,
            'guardian_id' => 4,
            'nombre' => 'Lynn',
            'apellido' => 'Powell',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '1824824',
            'fecha_nacimiento' => '2005/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 1,
            'guardian_id' => 5,
            'nombre' => 'Christian',
            'apellido' => 'Padilla',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '839483',
            'fecha_nacimiento' => '2008/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 3,
            'guardian_id' => 5,
            'nombre' => 'Claudia',
            'apellido' => 'Stapleton',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '4984289',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 4,
            'guardian_id' => 3,
            'nombre' => 'Karina',
            'apellido' => 'Bruce',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '9479384',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 4,
            'guardian_id' => 2,
            'nombre' => 'William',
            'apellido' => 'Bronson',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '6387935',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 5,
            'guardian_id' => 1,
            'nombre' => 'Tommy',
            'apellido' => 'Lumpkin',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '7384738',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 5,
            'guardian_id' => 3,
            'nombre' => 'Dean',
            'apellido' => 'Hopkins',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '6438742',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 5,
            'guardian_id' => 4,
            'nombre' => 'Rachel',
            'apellido' => 'Parsons',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '4729824',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 2,
            'guardian_id' => 2,
            'nombre' => 'Pearl',
            'apellido' => 'Sartin',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '8348734',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 4,
            'guardian_id' => 1,
            'nombre' => 'Ralph',
            'apellido' => 'McCleery',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '3872832',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 3,
            'guardian_id' => 5,
            'nombre' => 'Susan',
            'apellido' => 'Wentzel',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '1938234',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 2,
            'guardian_id' => 3,
            'nombre' => 'Sylvia',
            'apellido' => 'Bernabe',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '1429882',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 1,
            'guardian_id' => 1,
            'nombre' => 'Thomas',
            'apellido' => 'Mello',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '9827242',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 5,
            'guardian_id' => 2,
            'nombre' => 'Anna',
            'apellido' => 'Pinner',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '7284944',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nacionalidad_id' => 4,
            'guardian_id' => 4,
            'nombre' => 'Laura',
            'apellido' => 'Bryan',
            'documento_tipo' => 'Cédula de Identidad',
            'documento_numero' => '2742844',
            'fecha_nacimiento' => '1997/12/12',
            'sexo' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);
    }
}
