<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class HorarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('horarios')->insert([[
            'plan_curso_id' => 1,
            'dia' => 'Lunes',
            'estado' => 'Activo',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'plan_curso_id' => 1,
            'dia' => 'Martes',
            'estado' => 'Activo',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'plan_curso_id' => 1,
            'dia' => 'Miercoles',
            'estado' => 'Activo',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'plan_curso_id' => 1,
            'dia' => 'Jueves',
            'estado' => 'Activo',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'plan_curso_id' => 1,
            'dia' => 'Viernes',
            'estado' => 'Activo',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        DB::table('horarios_detalle')->insert([[
            'horario_id' => 1,
            'asignatura_id' => 1,
            'contrato_id' => 1,
            'hora' => '1',
            'hora_desde' => '07:00',
            'hora_hasta' => '07:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 2,
            'contrato_id' => 2,
            'hora' => '2',
            'hora_desde' => '07:40',
            'hora_hasta' => '08:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 3,
            'contrato_id' => 3,
            'hora' => '3',
            'hora_desde' => '08:20',
            'hora_hasta' => '09:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 4,
            'contrato_id' => 4,
            'hora' => '4',
            'hora_desde' => '09:20',
            'hora_hasta' => '10:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 5,
            'contrato_id' => 5,
            'hora' => '5',
            'hora_desde' => '10:00',
            'hora_hasta' => '10:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 6,
            'contrato_id' => 6,
            'hora' => '6',
            'hora_desde' => '10:40',
            'hora_hasta' => '11:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 1,
            'asignatura_id' => 7,
            'contrato_id' => 7,
            'hora' => '7',
            'hora_desde' => '11:20',
            'hora_hasta' => '12:00',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        DB::table('horarios_detalle')->insert([[
            'horario_id' => 2,
            'asignatura_id' => 1,
            'contrato_id' => 2,
            'hora' => '1',
            'hora_desde' => '07:00',
            'hora_hasta' => '07:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 2,
            'contrato_id' => 1,
            'hora' => '2',
            'hora_desde' => '07:40',
            'hora_hasta' => '08:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 3,
            'contrato_id' => 3,
            'hora' => '3',
            'hora_desde' => '08:20',
            'hora_hasta' => '09:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 4,
            'contrato_id' => 4,
            'hora' => '4',
            'hora_desde' => '09:20',
            'hora_hasta' => '10:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 5,
            'contrato_id' => 5,
            'hora' => '5',
            'hora_desde' => '10:00',
            'hora_hasta' => '10:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 6,
            'contrato_id' => 6,
            'hora' => '6',
            'hora_desde' => '10:40',
            'hora_hasta' => '11:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 2,
            'asignatura_id' => 7,
            'contrato_id' => 7,
            'hora' => '7',
            'hora_desde' => '11:20',
            'hora_hasta' => '12:00',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        DB::table('horarios_detalle')->insert([[
            'horario_id' => 3,
            'asignatura_id' => 1,
            'contrato_id' => 3,
            'hora' => '1',
            'hora_desde' => '07:00',
            'hora_hasta' => '07:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 2,
            'contrato_id' => 2,
            'hora' => '2',
            'hora_desde' => '07:40',
            'hora_hasta' => '08:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 3,
            'contrato_id' => 1,
            'hora' => '3',
            'hora_desde' => '08:20',
            'hora_hasta' => '09:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 4,
            'contrato_id' => 4,
            'hora' => '4',
            'hora_desde' => '09:20',
            'hora_hasta' => '10:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 5,
            'contrato_id' => 5,
            'hora' => '5',
            'hora_desde' => '10:00',
            'hora_hasta' => '10:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 6,
            'contrato_id' => 6,
            'hora' => '6',
            'hora_desde' => '10:40',
            'hora_hasta' => '11:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 3,
            'asignatura_id' => 7,
            'contrato_id' => 7,
            'hora' => '7',
            'hora_desde' => '11:20',
            'hora_hasta' => '12:00',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        DB::table('horarios_detalle')->insert([[
            'horario_id' => 4,
            'asignatura_id' => 1,
            'contrato_id' => 4,
            'hora' => '1',
            'hora_desde' => '07:00',
            'hora_hasta' => '07:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 2,
            'contrato_id' => 2,
            'hora' => '2',
            'hora_desde' => '07:40',
            'hora_hasta' => '08:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 3,
            'contrato_id' => 3,
            'hora' => '3',
            'hora_desde' => '08:20',
            'hora_hasta' => '09:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 4,
            'contrato_id' => 1,
            'hora' => '4',
            'hora_desde' => '09:20',
            'hora_hasta' => '10:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 5,
            'contrato_id' => 5,
            'hora' => '5',
            'hora_desde' => '10:00',
            'hora_hasta' => '10:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 6,
            'contrato_id' => 6,
            'hora' => '6',
            'hora_desde' => '10:40',
            'hora_hasta' => '11:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 4,
            'asignatura_id' => 7,
            'contrato_id' => 7,
            'hora' => '7',
            'hora_desde' => '11:20',
            'hora_hasta' => '12:00',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        DB::table('horarios_detalle')->insert([[
            'horario_id' => 5,
            'asignatura_id' => 1,
            'contrato_id' => 5,
            'hora' => '1',
            'hora_desde' => '07:00',
            'hora_hasta' => '07:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 2,
            'contrato_id' => 2,
            'hora' => '2',
            'hora_desde' => '07:40',
            'hora_hasta' => '08:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 3,
            'contrato_id' => 3,
            'hora' => '3',
            'hora_desde' => '08:20',
            'hora_hasta' => '09:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 4,
            'contrato_id' => 4,
            'hora' => '4',
            'hora_desde' => '09:20',
            'hora_hasta' => '10:00',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 5,
            'contrato_id' => 1,
            'hora' => '5',
            'hora_desde' => '10:00',
            'hora_hasta' => '10:40',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 6,
            'contrato_id' => 6,
            'hora' => '6',
            'hora_desde' => '10:40',
            'hora_hasta' => '11:20',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'horario_id' => 5,
            'asignatura_id' => 7,
            'contrato_id' => 7,
            'hora' => '7',
            'hora_desde' => '11:20',
            'hora_hasta' => '12:00',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

								// ------------------------------------------------------- 2 --------------------------------------------------
								DB::table('horarios')->insert([[
																																											'plan_curso_id' => 2,
																																											'dia' => 'Lunes',
																																											'estado' => 'Activo',
																																											'created_at' => now(),
																																											'updated_at' => now(),
																																							], [
																																											'plan_curso_id' => 2,
																																											'dia' => 'Martes',
																																											'estado' => 'Activo',
																																											'created_at' => now(),
																																											'updated_at' => now(),
																																							], [
																																											'plan_curso_id' => 2,
																																											'dia' => 'Miercoles',
																																											'estado' => 'Activo',
																																											'created_at' => now(),
																																											'updated_at' => now(),
																																							], [
																																											'plan_curso_id' => 2,
																																											'dia' => 'Jueves',
																																											'estado' => 'Activo',
																																											'created_at' => now(),
																																											'updated_at' => now(),
																																							], [
																																											'plan_curso_id' => 2,
																																											'dia' => 'Viernes',
																																											'estado' => 'Activo',
																																											'created_at' => now(),
																																											'updated_at' => now(),
																																							]]);

								DB::table('horarios_detalle')->insert([[
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 1,
																																																			'contrato_id' => 2,
																																																			'hora' => '1',
																																																			'hora_desde' => '07:00',
																																																			'hora_hasta' => '07:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 2,
																																																			'contrato_id' => 1,
																																																			'hora' => '2',
																																																			'hora_desde' => '07:40',
																																																			'hora_hasta' => '08:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 3,
																																																			'contrato_id' => 3,
																																																			'hora' => '3',
																																																			'hora_desde' => '08:20',
																																																			'hora_hasta' => '09:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 4,
																																																			'contrato_id' => 4,
																																																			'hora' => '4',
																																																			'hora_desde' => '09:20',
																																																			'hora_hasta' => '10:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 5,
																																																			'contrato_id' => 5,
																																																			'hora' => '5',
																																																			'hora_desde' => '10:00',
																																																			'hora_hasta' => '10:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 6,
																																																			'contrato_id' => 6,
																																																			'hora' => '6',
																																																			'hora_desde' => '10:40',
																																																			'hora_hasta' => '11:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 6,
																																																			'asignatura_id' => 7,
																																																			'contrato_id' => 7,
																																																			'hora' => '7',
																																																			'hora_desde' => '11:20',
																																																			'hora_hasta' => '12:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															]]);

								DB::table('horarios_detalle')->insert([[
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 1,
																																																			'contrato_id' => 2,
																																																			'hora' => '1',
																																																			'hora_desde' => '07:00',
																																																			'hora_hasta' => '07:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 2,
																																																			'contrato_id' => 1,
																																																			'hora' => '2',
																																																			'hora_desde' => '07:40',
																																																			'hora_hasta' => '08:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 3,
																																																			'contrato_id' => 3,
																																																			'hora' => '3',
																																																			'hora_desde' => '08:20',
																																																			'hora_hasta' => '09:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 4,
																																																			'contrato_id' => 4,
																																																			'hora' => '4',
																																																			'hora_desde' => '09:20',
																																																			'hora_hasta' => '10:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 5,
																																																			'contrato_id' => 5,
																																																			'hora' => '5',
																																																			'hora_desde' => '10:00',
																																																			'hora_hasta' => '10:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 6,
																																																			'contrato_id' => 6,
																																																			'hora' => '6',
																																																			'hora_desde' => '10:40',
																																																			'hora_hasta' => '11:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 7,
																																																			'asignatura_id' => 7,
																																																			'contrato_id' => 7,
																																																			'hora' => '7',
																																																			'hora_desde' => '11:20',
																																																			'hora_hasta' => '12:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															]]);

								DB::table('horarios_detalle')->insert([[
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 1,
																																																			'contrato_id' => 3,
																																																			'hora' => '1',
																																																			'hora_desde' => '07:00',
																																																			'hora_hasta' => '07:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 2,
																																																			'contrato_id' => 2,
																																																			'hora' => '2',
																																																			'hora_desde' => '07:40',
																																																			'hora_hasta' => '08:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 3,
																																																			'contrato_id' => 1,
																																																			'hora' => '3',
																																																			'hora_desde' => '08:20',
																																																			'hora_hasta' => '09:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 4,
																																																			'contrato_id' => 4,
																																																			'hora' => '4',
																																																			'hora_desde' => '09:20',
																																																			'hora_hasta' => '10:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 5,
																																																			'contrato_id' => 5,
																																																			'hora' => '5',
																																																			'hora_desde' => '10:00',
																																																			'hora_hasta' => '10:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 6,
																																																			'contrato_id' => 6,
																																																			'hora' => '6',
																																																			'hora_desde' => '10:40',
																																																			'hora_hasta' => '11:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 8,
																																																			'asignatura_id' => 7,
																																																			'contrato_id' => 7,
																																																			'hora' => '7',
																																																			'hora_desde' => '11:20',
																																																			'hora_hasta' => '12:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															]]);

								DB::table('horarios_detalle')->insert([[
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 1,
																																																			'contrato_id' => 4,
																																																			'hora' => '1',
																																																			'hora_desde' => '07:00',
																																																			'hora_hasta' => '07:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 2,
																																																			'contrato_id' => 2,
																																																			'hora' => '2',
																																																			'hora_desde' => '07:40',
																																																			'hora_hasta' => '08:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 3,
																																																			'contrato_id' => 3,
																																																			'hora' => '3',
																																																			'hora_desde' => '08:20',
																																																			'hora_hasta' => '09:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 4,
																																																			'contrato_id' => 1,
																																																			'hora' => '4',
																																																			'hora_desde' => '09:20',
																																																			'hora_hasta' => '10:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 5,
																																																			'contrato_id' => 5,
																																																			'hora' => '5',
																																																			'hora_desde' => '10:00',
																																																			'hora_hasta' => '10:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 6,
																																																			'contrato_id' => 6,
																																																			'hora' => '6',
																																																			'hora_desde' => '10:40',
																																																			'hora_hasta' => '11:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 9,
																																																			'asignatura_id' => 7,
																																																			'contrato_id' => 7,
																																																			'hora' => '7',
																																																			'hora_desde' => '11:20',
																																																			'hora_hasta' => '12:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															]]);

								DB::table('horarios_detalle')->insert([[
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 1,
																																																			'contrato_id' => 5,
																																																			'hora' => '1',
																																																			'hora_desde' => '07:00',
																																																			'hora_hasta' => '07:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 2,
																																																			'contrato_id' => 2,
																																																			'hora' => '2',
																																																			'hora_desde' => '07:40',
																																																			'hora_hasta' => '08:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 3,
																																																			'contrato_id' => 3,
																																																			'hora' => '3',
																																																			'hora_desde' => '08:20',
																																																			'hora_hasta' => '09:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 4,
																																																			'contrato_id' => 4,
																																																			'hora' => '4',
																																																			'hora_desde' => '09:20',
																																																			'hora_hasta' => '10:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 5,
																																																			'contrato_id' => 1,
																																																			'hora' => '5',
																																																			'hora_desde' => '10:00',
																																																			'hora_hasta' => '10:40',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 6,
																																																			'contrato_id' => 6,
																																																			'hora' => '6',
																																																			'hora_desde' => '10:40',
																																																			'hora_hasta' => '11:20',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															], [
																																																			'horario_id' => 10,
																																																			'asignatura_id' => 7,
																																																			'contrato_id' => 7,
																																																			'hora' => '7',
																																																			'hora_desde' => '11:20',
																																																			'hora_hasta' => '12:00',
																																																			'created_at' => now(),
																																																			'updated_at' => now(),
																																															]]);
    }
}
